import '@/styles/globals.scss';
import type { AppProps } from 'next/app';
import Head from "next/head";
import { SessionProvider } from "next-auth/react"

export default ({ Component, pageProps }: AppProps) => {
  return (
    <SessionProvider session={pageProps.session}>
      <Head>
        <title>Picsou</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
      </Head>
      <Component {...pageProps} />
    </SessionProvider>
  )
}
